### ISSUE TITLE
Handle genres

### ISSUE THREAD

**Issue by Chiisato** [KnightHawk3/Hummingbird#7]
How can I output genres in a neat format? Using result.genres results in a ugly formatted list, such as 
[{'name': 'Action'}, {'name': 'Drama'}, {'name':
                 | 'Horror'}, {'name': 'Vampire'}, {'name': 'Demons'}]

**Comment by KnightHawk3** [comment]
I can't remember how this works, but you could transform the output like so.

genre = [x for x['name'] in YourList]

I think I might start work on this project again, I gave up about a year ago because I was sick of the API, but maybe it's improved :)

**Comment by Chiisato** [comment]
I'll give it a try, using your wrapper and their api to allow users on irc to search the database for anime, haven't really found another wrapper for either MAL or anidb that works well.
